import {rankingBundleToDelibData} from '../public/delib-data-core.js';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {describe,it,expect} from 'vitest';
import {importExchange,validateExchange,exchangeToCsv,mergeExchange,withdrawExchange,nativeAdapters,exchangeToSensemaker} from '../public/exchange-core.js';
import {parseTttcCsv} from '../public/tttc-csv-core.js';
import {participantJourney} from '../public/persona-core.js';
const fixture=tool=>JSON.parse(readFileSync(new URL(`../public/data/exchange-examples/${tool}.json`,import.meta.url),'utf8'));
const convert=(tool,v=fixture(tool))=>importExchange(v,{tool,sha256:createHash('sha256').update(JSON.stringify(v)).digest('hex'),simulated:true});
describe('source-preserving exchange',()=>{
 it.each(nativeAdapters)('%s: retains private method data and survives a JSON round trip',tool=>{const b=convert(tool);expect(validateExchange(JSON.parse(JSON.stringify(b)))).toEqual(b);expect(b.records.length).toBeGreaterThan(0);expect(b.losses.length).toBeGreaterThan(0);expect(JSON.stringify(b.sources)).not.toContain('Fictional caregiver');});
 it('keeps scales and consent types out of participant text transfer',()=>{const b=convert('form');expect(b.records[1].fields.answer).toBe(3);expect(()=>exchangeToCsv(b)).toThrow(/consent/);const out=exchangeToCsv(b,{reviewed:true});const rows=parseTttcCsv({text:out.csv,label:'fixture'}).rows;expect(rows).toHaveLength(1);expect(rows[0].comment).toBe(b.records[0].text);expect(rows[0].interview).toBe('');expect(out.manifest.mappings[0].recordId).toBe(b.records[0].id);});
 it('never turns interviewer or generated replies into participant voices',()=>{const interview=convert('harmonica');const out=exchangeToCsv(interview,{reviewed:true});expect(out.csv).not.toContain('What makes arrival');expect(out.csv).toContain('I need a place');const reply=convert('reply');expect(exchangeToCsv(reply,{reviewed:true}).csv).not.toContain('Draft:');expect(reply.records[1].relations[0].type).toBe('responds');});
 it('reconnects a report only with an explicit manifest and matching source text',()=>{const form=convert('form'),tree=convert('tttc'),transfer=exchangeToCsv(form,{reviewed:true}).manifest;const merged=mergeExchange([form,tree],transfer);expect(merged.externalSources).toEqual([]);expect(merged.records.find(r=>r.kind==='quote').relations[0].ref).toBe(form.records[0].id);const bad=structuredClone(tree);bad.records.find(r=>r.kind==='quote').text='Fabricated quotation';expect(()=>mergeExchange([form,bad],transfer)).toThrow(/Quote/);});
 it('withdrawal blocks descendants and removes retained native text from onward packages',()=>{const form=convert('form'),tree=convert('tttc'),merged=mergeExchange([form,tree],exchangeToCsv(form,{reviewed:true}).manifest);const withdrawn=withdrawExchange(merged,form.records[0].id,{by:'Facilitator',reason:'Speaker withdrew'});expect(withdrawn.records.find(r=>r.kind==='theme').status).toBe('needs-review');expect(withdrawn.sources.every(s=>Object.keys(s.methodData).length===0)).toBe(true);expect(()=>exchangeToCsv(withdrawn,{reviewed:true})).toThrow(/eligible/);expect(withdrawn.privacy.remoteDeletionConfirmed).toBe(false);expect(merged.tombstones).toEqual([]);});
 it('preserves different method semantics without exporting scores as voices',()=>{for(const tool of ['values','budget','check'])expect(()=>exchangeToCsv(convert(tool),{reviewed:true})).toThrow(/eligible/);expect(convert('budget').records[0].fields.support).toBeCloseTo(2/3);const a=convert('argument');expect(a.records[1].relations).toEqual([{ref:a.records[0].id,type:'opposes'}]);expect(convert('proposals').records[0].fields.version).toBe(2);expect(JSON.stringify(convert('maple'))).not.toContain('Fictional caregiver');});
 it('rejects re-enabled records after withdrawal and erases root answer fields',()=>{const b=convert('form'),w=withdrawExchange(b,b.records[0].id,{by:'Host',reason:'Requested withdrawal'});expect(w.records[0].fields).toEqual({});w.records[0].transferEligible=true;w.records[0].status='reviewed';expect(()=>validateExchange(w)).toThrow(/Withdrawal/);});
 it('rejects secrets, duplicate IDs, cycles and unmatched reply questions',()=>{const f=fixture('form');f.adminToken='private';expect(()=>convert('form',f)).toThrow(/credentials/);const b=convert('form');b.records.push({...b.records[0]});expect(()=>validateExchange(b)).toThrow(/Duplicate/);const r=fixture('reply');r.loopbacks[0].qid='missing';expect(()=>convert('reply',r)).toThrow(/source/);const cycle=convert('harmonica');cycle.records[0].relations=[{ref:cycle.records[1].id,type:'context'}];expect(()=>validateExchange(cycle)).toThrow(/Cyclic/);});
 it('does not silently truncate text or overwrite conflicting source revisions',()=>{const f=fixture('form');f.responses[0].answers.q1='x'.repeat(2001);expect(()=>exchangeToCsv(convert('form',f),{reviewed:true})).toThrow(/2000/);expect(()=>mergeExchange([convert('form'),convert('form',f)])).toThrow(/Conflicting/);});
});
describe('fictional journeys',()=>{
 it('links every person and every round to actual demo sources without claiming real attendance',()=>{const b=JSON.parse(readFileSync(new URL('../public/data/flow-demo.json',import.meta.url)));for(const p of b.participants){const r=participantJourney(b,p.id);expect(r).toHaveLength(3);r.forEach((round,ri)=>{expect(round.steps).toHaveLength(8);round.steps.forEach(s=>s.sourceRefs.forEach(id=>expect(b.rounds[ri].artifacts.find(a=>a.id===id).participantRef).toBe(p.id)));});}b.simulated=false;expect(()=>participantJourney(b,'p01')).toThrow(/fictional/);});
});

it('exports Sensemaker backend comments without fabricating missing votes',()=>{const b=convert('civic-talk'),out=exchangeToSensemaker(b,{reviewed:true});expect(out.json.comments).toHaveLength(1);expect(out.json.comments[0].text).toBe(b.records[0].text);expect(out.json.comments[0]).not.toHaveProperty('voteInfo');expect(JSON.stringify(b)).not.toContain('fictional@example.invalid');expect(b.losses.some(l=>l.path==='/opinions/2'&&l.action==='blocked')).toBe(true);});

it('imports Polis/Ranker delib-data while keeping votes out of source text',()=>{const b=convert('delib-data');expect(b.records[1].fields.count).toBe(1);expect(b.records[2].fields.counts.agree).toBe(1);expect(b.records[1].relations[0].ref).toBe(b.records[0].id);expect(exchangeToCsv(b,{reviewed:true}).manifest.rowCount).toBe(1);expect(JSON.stringify(b)).not.toContain('Fictional caregiver');const bad=fixture('delib-data');bad.responses[0].subjectRef='absent';expect(()=>convert('delib-data',bad)).toThrow(/lineage/);});

it('consumes the actual Power Ranker adapter output, without turning rankings into voices',()=>{const ranking=JSON.parse(readFileSync(new URL('./fixtures/power-ranker-session.json',import.meta.url)));const canonical=rankingBundleToDelibData(ranking);const b=convert('delib-data',canonical);expect(b.records.some(r=>r.fields.type==='relative-ranking')).toBe(true);expect(()=>exchangeToCsv(b,{reviewed:true})).toThrow(/eligible/);b.sources[0].methodData.responses.forEach(r=>expect(r).not.toHaveProperty('participantRef'));b.records.forEach(r=>expect(r.fields).not.toHaveProperty('participantRef'));});
