import {describe,it,expect} from 'vitest';
import {createProject,validateProject,currentRound,record,reviewRecord,reviseRecord,nextRound,allRecords,traceVoice} from '../public/workspace-core.js';
import {setCommitment,setDisposition,saveParticipation,latest,openParticipation,voiceTrailExport,roundFollowups} from '../public/facilitation-core.js';
const setup=()=>{const p=createProject({title:'School gate',audience:'Caregivers',goal:'Keep access',deadline:'2026-12-01'});const v=record('statement','Keep accessible drop-off',{tool:'form',id:'source-1'}),r=record('reply','Test a protected bay',{tool:'reply',id:'reply-1'},[v.id]);currentRound(p).artifacts.push(v,r);currentRound(p).inputs.push(v.id);return {p,v,r};};
const owner={owner:'School contact',reviewOn:'2026-12-01',by:'Host'};
const commitment=(status,extra={})=>({...owner,status,note:'Confirmed scope and review conditions',authorityConfirmed:true,...extra});
const gap={...owner,group:'Shift-working caregivers',barrier:'Cannot attend daytime meetings',action:'Offer an evening listening session',note:'No accessible time was offered',status:'missing'};
const extend=p=>nextRound(p,{reason:'Hear caregivers',owner:'Host',date:'2026-12-10',phase:'recruit'});
describe('facilitation work is attributed and survives successive rounds',()=>{
 it('accepts old v1 projects without inventing checks, commitments or participation coverage',()=>{const {p,r}=setup();delete p.view.mode;expect(validateProject(p)).toBe(p);expect(r.commitments).toBeUndefined();expect(currentRound(p).participation).toBeUndefined();reviewRecord(p,r.id,{reviewer:'Host'});expect(r.commitments).toBeUndefined();expect(r.dispositions).toBeUndefined();});
 it('requires wording review, explicit authority and valid transitions, without partial writes',()=>{const {p,r}=setup();expect(()=>setCommitment(p,r.id,commitment('confirmed'))).toThrow(/Review/);reviewRecord(p,r.id,{reviewer:'Host'});expect(()=>setCommitment(p,r.id,commitment('confirmed',{authorityConfirmed:false}))).toThrow(/confirmation/);expect(()=>setCommitment(p,r.id,commitment('committed'))).toThrow(/transition/);expect(r.commitments).toBeUndefined();setCommitment(p,r.id,commitment('confirmed'));setCommitment(p,r.id,commitment('committed'));expect(r.commitments).toHaveLength(2);expect(latest(r.commitments).status).toBe('committed');expect(validateProject(p)).toBe(p);});
 it('requires owner, real calendar date, recorder and reasons for each outcome',()=>{const {p,v}=setup();for(const extra of [{reason:''},{owner:''},{by:''},{reviewOn:'2026-02-30'},{status:'consensus'}]){expect(()=>setDisposition(p,v.id,{...owner,status:'not-adopted',reason:'Safety evidence needs review',...extra})).toThrow();expect(v.dispositions).toBeUndefined();}setDisposition(p,v.id,{...owner,status:'not-adopted',reason:'Keep wheelchair access; review another location'});expect(latest(v.dispositions).reason).toContain('wheelchair');});
 it('retains previous decisions and resets commitments on a textual revision',()=>{const {p,v,r}=setup();reviewRecord(p,r.id,{reviewer:'Host'});setCommitment(p,r.id,commitment('confirmed'));setCommitment(p,r.id,commitment('committed'));const revision=reviseRecord(p,r.id,'Use another bay','Editor');expect(revision.commitments).toBeUndefined();expect(revision.review.checked).toBe(false);expect(()=>setCommitment(p,r.id,commitment('piloting'))).toThrow(/latest revision/);setDisposition(p,v.id,{...owner,status:'deferred',reason:'Need a site visit'});setDisposition(p,v.id,{...owner,status:'adopted',reason:'Site visit supports keeping access'});expect(v.dispositions.map(e=>e.status)).toEqual(['deferred','adopted']);expect(r.commitments).toHaveLength(2);});
 it('carries unresolved references through three rounds, including reviewed but unaddressed voices',()=>{const {p,v,r}=setup();reviewRecord(p,v.id,{reviewer:'Host'});reviewRecord(p,r.id,{reviewer:'Host'});setCommitment(p,r.id,commitment('draft',{authorityConfirmed:false}));extend(p);expect(currentRound(p).inputs).toContain(v.id);expect(currentRound(p).inputs).toContain(r.id);extend(p);expect(currentRound(p).inputs).toContain(v.id);expect(currentRound(p).inputs).toContain(r.id);expect(validateProject(p)).toBe(p);});
 it('closes a commitment only after an explicit attributed review, preserving history',()=>{const {p,r}=setup();reviewRecord(p,r.id,{reviewer:'Host'});for(const status of ['confirmed','committed','piloting','review-due','closed'])setCommitment(p,r.id,commitment(status));expect(roundFollowups(p).map(a=>a.id)).not.toContain(r.id);expect(r.commitments).toHaveLength(5);setCommitment(p,r.id,commitment('confirmed'));expect(roundFollowups(p).map(a=>a.id)).toContain(r.id);});
 it('keeps participation barriers and history across rounds without copying resolved gaps',()=>{const {p}=setup();const first=saveParticipation(p,'',gap);saveParticipation(p,first.id,{...gap,status:'invited',note:'Evening session invitation prepared'});extend(p);const second=currentRound(p).participation[0];expect(second.id).not.toBe(first.id);expect(second.carriedFrom).toBe(first.id);expect(second.history).toHaveLength(2);saveParticipation(p,second.id,{...gap,status:'heard',note:'Host recorded the evening accounts'});expect(latest(p.rounds[0].participation[0].history).status).toBe('invited');expect(openParticipation(currentRound(p))).toHaveLength(0);extend(p);expect(currentRound(p).participation).toEqual([]);expect(validateProject(JSON.parse(JSON.stringify(p)))).toEqual(p);});
 it('rejects forged extension histories and broken gap lineage in imported projects',()=>{const {p,r}=setup();reviewRecord(p,r.id,{reviewer:'Host'});setCommitment(p,r.id,commitment('confirmed'));const bad=structuredClone(p);bad.rounds[0].artifacts[1].commitments[0].status='closed';expect(()=>validateProject(bad)).toThrow(/transition/);saveParticipation(p,'',gap);const broken=structuredClone(p);broken.rounds[0].participation[0].carriedFrom='unknown';expect(()=>validateProject(broken)).toThrow(/lineage/);});
 it('exports the voice outcome and commitment history without the private participation register',()=>{const {p,v,r}=setup();setDisposition(p,v.id,{...owner,status:'deferred',reason:'Revisit after the access check'});reviewRecord(p,r.id,{reviewer:'Host'});setCommitment(p,r.id,commitment('confirmed'));saveParticipation(p,'',gap);const receipt=voiceTrailExport(p,traceVoice(p,v.id));expect(receipt.records[0].dispositions[0].reason).toContain('Revisit');expect(receipt.records[1].commitments[0].owner).toBe(owner.owner);expect(JSON.stringify(receipt)).not.toContain(gap.barrier);expect(receipt.exportedAt).toBeTruthy();expect(allRecords(p)).toHaveLength(2);});
});
