import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createProject,record,validateProject,reviseRecord,reviewRecord} from '../public/workspace-core.js';
import {requestCorrection,resolveCorrection,saveSession,sessionCounts,startProgression,advanceProgression,validateOperations,correctionImpact} from '../public/operations-core.js';
import {operationsDemo} from '../public/operations-demo.js';
const base=()=>{const p=createProject({title:'Test',goal:'Test',audience:'Test',deadline:'2026-12-01'}),voice=record('statement','Original',{tool:'form',id:'1'}),proposal=record('proposal','Option',{tool:'facilitator',id:'2'},[voice.id]);p.rounds[0].artifacts.push(voice,proposal);return {p,voice,proposal};};
const by='Recorder',reason='Documented reason',owner='Owner',due='2026-12-01';
const session=()=>({status:'planned',title:'Session',date:'2026-12-01',mode:'offline',owner,by,notes:'Purpose and support',agenda:[{title:'Discuss',minutes:20}],groups:['A'],observations:[{participant:'local-1',group:'A',invited:true,attended:false,spoke:false,voted:false,barrier:'Night shift'}],evaluations:[]});
describe('accountable local facilitation',()=>{
 it('keeps immutable originals, resolution reasons and downstream impact',()=>{const {p,voice,proposal}=base(),c=requestCorrection(p,voice.id,{reason,owner,due,by});expect(correctionImpact(p,voice.id)).toEqual([voice.id,proposal.id]);expect(()=>resolveCorrection(p,c.id,{status:'accepted',reason,by})).toThrow();const v=reviseRecord(p,voice.id,'Corrected',by);resolveCorrection(p,c.id,{status:'accepted',reason,by,replacementRef:v.id});expect(voice.text).toBe('Original');expect(p.operations.corrections[0].history).toHaveLength(2);expect(()=>validateProject(JSON.parse(JSON.stringify(p)))).not.toThrow();expect(()=>resolveCorrection(p,c.id,{status:'declined',reason,by})).toThrow();});
 it('rejects invalid deadlines and cross-issue correction references transactionally',()=>{const {p}=base();for(const args of [{id:'missing',due},{id:p.rounds[0].artifacts[0].id,due:'2026-02-30'}]){const before=JSON.stringify(p);expect(()=>requestCorrection(p,args.id,{reason,owner,due:args.due,by})).toThrow();expect(JSON.stringify(p)).toBe(before);}});
 it('distinguishes attendance stages and requires real feedback before reviewed',()=>{const {p}=base(),s=saveSession(p,null,session());expect(sessionCounts(s)).toEqual({invited:1,attended:0,spoke:0,voted:0});const held={...session(),status:'held',observations:[{...session().observations[0],attended:true,spoke:true}]};saveSession(p,s.id,held);expect(()=>saveSession(p,s.id,{...held,status:'reviewed'})).toThrow();saveSession(p,s.id,{...held,status:'reviewed',evaluations:[{participant:'local-1',heard:4,understood:null,fair:3,note:'Needs more time'}]});expect(()=>validateProject(p)).not.toThrow();});
 for(const change of [s=>s.observations[0].spoke=true,s=>s.groups=[],s=>s.agenda[0].minutes=-1,s=>s.observations.push(s.observations[0]),s=>s.evaluations=[{participant:'missing',heard:5,understood:5,fair:5,note:''}]])it('rejects fabricated or malformed session states',()=>{const {p}=base(),s=session();change(s);expect(()=>saveSession(p,null,s)).toThrow();expect(p.operations).toBeUndefined();});
 it('enforces progression rules, evidence, review and correction holds',()=>{const {p,voice,proposal}=base(),g=startProgression(p,{proposalRef:proposal.id,rule:'Two members, two supporters',owner,quorum:2,minSupport:2,by}),entry={stage:'review',reason,evidenceRefs:[voice.id],eligible:3,support:2,oppose:1,abstain:0,minorityNote:'Objection retained in next round',by};advanceProgression(p,g.id,entry);expect(()=>advanceProgression(p,g.id,{...entry,stage:'ready'})).toThrow();reviewRecord(p,proposal.id,{reviewer:by});const c=requestCorrection(p,proposal.id,{reason,owner,due,by});expect(()=>advanceProgression(p,g.id,{...entry,stage:'ready'})).toThrow();resolveCorrection(p,c.id,{status:'declined',reason,by});advanceProgression(p,g.id,{...entry,stage:'ready'});expect(p.operations.progressions[0].history.at(-1).proposalReviewed).toBe(true);expect(()=>advanceProgression(p,g.id,{...entry,stage:'reviewed'})).toThrow();reviewRecord(p,proposal.id,{reviewer:by,checked:false});expect(()=>validateOperations(p)).not.toThrow();});
 it.each(['zh','en'])('bilingual fictional workflow survives full workspace reload: %s',lang=>{const data=JSON.parse(readFileSync(new URL('../public/data/flow-demo.json',import.meta.url))),p=operationsDemo(data,lang);expect(()=>validateProject(JSON.parse(JSON.stringify(p)))).not.toThrow();expect(p.simulated).toBe(true);expect(p.operations.sessions[0].history).toHaveLength(3);expect(sessionCounts(p.operations.sessions[0])).toEqual({invited:3,attended:2,spoke:1,voted:2});});
 it('reopens reviewed descendants after an accepted source correction',()=>{const {p,voice,proposal}=base();reviewRecord(p,proposal.id,{reviewer:by});const c=requestCorrection(p,voice.id,{reason,owner,due,by}),v=reviseRecord(p,voice.id,'Corrected',by);resolveCorrection(p,c.id,{status:'accepted',reason,by,replacementRef:v.id});expect(proposal.review.checked).toBe(false);expect(p.events.at(-1)).toMatchObject({type:'reopen',recordId:proposal.id});expect(()=>validateProject(p)).not.toThrow();});
 it('holds downstream proposals when an upstream source has an unresolved correction',()=>{const {p,voice,proposal}=base(),g=startProgression(p,{proposalRef:proposal.id,rule:'Two supporters',owner,quorum:2,minSupport:2,by});requestCorrection(p,voice.id,{reason,owner,due,by});const before=JSON.stringify(p);expect(()=>advanceProgression(p,g.id,{stage:'review',reason,evidenceRefs:[voice.id],eligible:2,support:2,oppose:0,abstain:0,minorityNote:'Pending source correction',by})).toThrow(/corrections/);expect(JSON.stringify(p)).toBe(before);});
});
