import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {buildPolisAnalysis,normalizePolisAnalysis} from '../public/polis-analysis-core.js';
import {importExchange,exchangeToCsv,withdrawExchange} from '../public/exchange-core.js';
import {createProject,validateProject} from '../public/workspace-core.js';
import {planNativeImport,applyNativeImport} from '../public/workspace-import-core.js';
const raw=()=>JSON.parse(readFileSync(new URL('./fixtures/polis-analysis-input.json',import.meta.url)));
const convert=p=>importExchange(p,{tool:'polis-analysis',sha256:'a'.repeat(64),simulated:true});
const synthesis=r=>({version:'v1',privacyVersion:2,status:'ready',generationMode:'ai',model:'test-model',generatedAt:1790164900000,mathRevision:42,lang:'en',provenance:{generatedAt:1790164900000,mathRevision:42,participantCount:r.nParticipantsTotal,clusteredCount:r.nParticipantsClustered,statementCount:r.nStatements,voteCount:r.nVotes,groupCount:r.groups.length},overview:{summary:'Fictional model overview',citedStatementIds:[1,2]},themes:[],commonGround:{keyPoints:[]},groupPortraits:[],tensions:[]});
describe('Polis aggregate analysis bridge',()=>{
 it('retains actual upstream aggregate math, redaction and coverage without personal coordinates',()=>{const r=raw();r.result.you={group:0,x:1,y:1};const p=buildPolisAnalysis(r),again=normalizePolisAnalysis(p);expect(again).toEqual(p);expect(p.analysis.groups).toHaveLength(2);expect(p.analysis.coverage).toEqual({voteMatrix:1,clusteredShare:1});expect(p.analysis.bridging).not.toBeNull();expect(JSON.stringify(p)).not.toContain('points');expect(JSON.stringify(p)).not.toContain('fictional-0');});
 it('round-trips through exchange and workspace without seeds or statistics becoming participant speech',()=>{const p=buildPolisAnalysis(raw()),b=convert(p),w=createProject({title:'Test',goal:'Test',audience:'Test',deadline:'2026-12-01',simulated:true});w.simulated=true;const plan=planNativeImport(w,{bundle:b,fileSha256:'b'.repeat(64)});applyNativeImport(w,plan);expect(()=>validateProject(JSON.parse(JSON.stringify(w)))).not.toThrow();expect(b.records.find(r=>r.originalId==='statement-1').transferEligible).toBe(false);expect(exchangeToCsv(b,{reviewed:true}).manifest.rowCount).toBe(7);expect(b.records.find(r=>r.originalId==='analysis').fields.groups).toHaveLength(2);});
 it('keeps model text and multi-source citation links distinct, and marks the revision gap',()=>{const r=raw();r.synthesis=synthesis(r.result.result);const p=buildPolisAnalysis(r),b=convert(p);expect(p.synthesis.alignment).toContain('counts-only');const summary=b.records.find(r=>r.kind==='theme');expect(summary.origin).toBe('model');expect(summary.relations).toHaveLength(2);expect(summary.transferEligible).toBe(false);expect(normalizePolisAnalysis(p).synthesis.passages).toEqual(p.synthesis.passages);const withdrawn=withdrawExchange(b,b.records[0].id,{reason:'test',by:'test'});expect(withdrawn.records.find(r=>r.kind==='theme').status).toBe('needs-review');});
 for(const mutation of [r=>r.result.result.statementStats[0].agrees++,r=>r.result.result.groups[0].statementStats[0].sid=999,r=>r.result.result.groups[0].statsRedacted=true,r=>r.result.result.nParticipantsClustered=999,r=>r.statements[0].agrees++,r=>r.statements[1].statementId=r.statements[0].statementId])it('rejects inconsistent counts, hidden-cell claims and invalid source references',()=>{const r=raw();mutation(r);expect(()=>buildPolisAnalysis(r)).toThrow();});
 it('rejects stale or broken synthesis citations',()=>{for(const alter of [s=>s.isStale=true,s=>s.overview.citedStatementIds=[999],s=>s.provenance.voteCount=0]){const r=raw();r.synthesis=synthesis(r.result.result);alter(r.synthesis);expect(()=>buildPolisAnalysis(r)).toThrow();}});
 it('validates three pinned public teaching subsets without inventing votes, groups or author roles',()=>{const manifest=JSON.parse(readFileSync(new URL('../public/data/polis-datasets.json',import.meta.url)));expect(manifest).toHaveLength(3);for(const d of manifest){const p=normalizePolisAnalysis(JSON.parse(readFileSync(new URL('../public'+d.path,import.meta.url))));expect(p.statements).toHaveLength(6);expect(p.analysis).toBeNull();expect(p.statements.every(s=>s.passes===null&&s.isSeed===null)).toBe(true);expect(p.evidence.sha256).toMatch(/^[a-f0-9]{64}$/);const b=convert(p);expect(b.records.every(r=>!r.transferEligible)).toBe(true);expect(p.sourceRevision).toBe('3be5785c3f5975d31f4578ee8bbf4426d45b7bf2');}});
});
