import {describe,it,expect} from 'vitest';
import {createProject,record,validateProject,traceVoice} from '../public/workspace-core.js';
import {planTransfer,addTransfer,advanceTransfer} from '../public/workspace-transfer-core.js';
import {workspaceFlow} from '../public/workspace-flow-core.js';
import {recordSetting} from '../public/workspace-setting-core.js';
const setup=()=>{const p=createProject({title:'School street',audience:'Families',goal:'Review access',deadline:'2026-12-01'}),r=p.rounds[0];const a=record('statement','Keep accessible arrival.',{tool:'form',id:'a'}),b=record('statement','Keep delivery access.',{tool:'form',id:'b'});r.artifacts.push(a,b);r.inputs.push(a.id,b.id);const theme=record('theme','Review both access needs.',{tool:'tttc',id:'t'},[a.id,b.id]);r.artifacts.push(theme);return {p,r,a,b,theme};};
describe('observed workspace flow',()=>{
 it('uses source lineage and does not infer a setting from Form or TTTC',()=>{const {p,a}=setup(),m=workspaceFlow(p,{voiceId:a.id});expect(m.nodes.map(n=>n.recordId)).toEqual(traceVoice(p,a.id).map(a=>a.id));expect(m.nodes.every(n=>n.setting==='unknown')).toBe(true);expect(m.transfers).toHaveLength(0);});
 it('excludes another person’s contextual reply from a selected voice path',()=>{const {p,r,a,b,theme}=setup();const reply=record('reply','Delivery draft',{tool:'reply',id:'reply'},[b.id,theme.id]);reply.relations=[{ref:b.id,type:'responds'},{ref:theme.id,type:'context'}];r.artifacts.push(reply);expect(workspaceFlow(p,{voiceId:a.id}).nodes.some(n=>n.recordId===reply.id)).toBe(false);});
 it('never animates a download into remote delivery',()=>{const {p,a}=setup(),t=addTransfer(p,planTransfer(p,{tool:'tttc'}));advanceTransfer(t,'exported');const m=workspaceFlow(p,{voiceId:a.id});expect(m.transfers[0].state).toBe('exported');expect(m.edges.filter(e=>e.to===`transfer:${t.id}`).every(e=>!e.replay)).toBe(true);expect(m.edges.some(e=>e.from===`transfer:${t.id}`)).toBe(false);validateProject(p);});
 it('draws result edges only after recorded reconnection',()=>{const {p,theme}=setup(),t=addTransfer(p,planTransfer(p,{tool:'tttc'}));advanceTransfer(t,'submitted');advanceTransfer(t,'received',{activityId:'abcdefghij'});advanceTransfer(t,'completed');expect(workspaceFlow(p).edges.some(e=>e.from===`transfer:${t.id}`)).toBe(false);advanceTransfer(t,'reconnected',{outputRefs:[theme.id]});expect(workspaceFlow(p).edges).toContainEqual({from:`transfer:${t.id}`,to:theme.id,type:'reconnected',replay:true});});
 it('keeps uncertain outcomes distinct and does not backfill legacy service links',()=>{const {p,r,a}=setup(),t=addTransfer(p,planTransfer(p,{tool:'tttc'}));advanceTransfer(t,'submitted');advanceTransfer(t,'uncertain');r.connections.reply={id:'abcdefghij',inputRefs:[a.id],contextRefs:[]};expect(workspaceFlow(p).transfers.map(t=>t.state)).toEqual(['uncertain']);expect(workspaceFlow(p).edges.filter(e=>e.to===`transfer:${t.id}`).every(e=>!e.replay)).toBe(true);});
 it('reports truncation and preserves cross-round carry without inventing service events',()=>{const {p,a}=setup();const brief=record('brief','Follow up',{tool:'facilitator',id:'next'},[a.id]);p.rounds.push({id:'round-2',title:'Round 2',step:0,artifacts:[brief],inputs:[a.id],connections:{},next:null});expect(workspaceFlow(p,{voiceId:a.id}).carry).toEqual([{recordId:a.id,roundId:'round-2'}]);expect(workspaceFlow(p,{limit:1}).omitted).toBe(2);expect(workspaceFlow(p).transfers).toEqual([]);});
 it('does not mutate the project when rendering a model',()=>{const {p}=setup(),before=JSON.stringify(p);workspaceFlow(p);expect(JSON.stringify(p)).toBe(before);});
});
describe('attributed setting observations',()=>{
 it('preserves earlier observations, independent from voice text and review, and reloads optional flow state',()=>{const {p,a}=setup();recordSetting(p,a.id,{setting:'online',by:'Host',note:'Collected at the online session.'});recordSetting(p,a.id,{setting:'in-person',by:'Host',note:'Correction: this note was transcribed from a meeting.'});p.view.tab='flow';p.view.flowVoice=a.id;expect(validateProject(JSON.parse(JSON.stringify(p)))).toEqual(p);expect(a.settingHistory).toHaveLength(2);expect(a.review.checked).toBe(false);expect(workspaceFlow(p).nodes.find(n=>n.recordId===a.id).setting).toBe('in-person');});
 it('rejects missing attribution and invalid settings without changing history',()=>{const {p,a}=setup();for(const change of [{setting:'both',by:'Host',note:'Guess'},{setting:'online',by:'',note:'No attribution'},{setting:'online',by:'Host',note:''}])expect(()=>recordSetting(p,a.id,change)).toThrow();expect(a).not.toHaveProperty('settingHistory');expect(()=>validateProject({...p,view:{...p.view,flowVoice:'missing'}})).toThrow(/voice/);});
});
