import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {importExchange,nativeAdapters,withdrawExchange} from '../public/exchange-core.js';
import {createProject,validateProject,allRecords,roundSources,reviewRecord,record,traceVoice,nextRound} from '../public/workspace-core.js';
import {planTransfer,transferCandidates,addTransfer,advanceTransfer} from '../public/workspace-transfer-core.js';
import {readNativeFile,planNativeImport,applyNativeImport,nativeRestrictions,compareImports} from '../public/workspace-import-core.js';
const fixture=t=>JSON.parse(readFileSync(new URL(`../public/data/exchange-examples/${t}.json`,import.meta.url)));
const project=()=>({...createProject({title:'School access',audience:'Families',goal:'Keep access usable',deadline:'2026-12-01'}),simulated:true});
const input=(tool,data=fixture(tool))=>({fileSha256:'a'.repeat(64),bundle:importExchange(data,{tool,simulated:true,sha256:'a'.repeat(64)})});
const load=(p,data,opts)=>{const plan=planNativeImport(p,data,opts);applyNativeImport(p,plan);validateProject(p);return plan;};
function transfer(p,tool){if(tool==='reply')for(const a of allRecords(p).filter(a=>a.kind==='theme'))reviewRecord(p,a.id,{reviewer:'Facilitator'});const t=addTransfer(p,planTransfer(p,{tool}));advanceTransfer(t,'exported');return t;}
const tttc=(source,quoteText=source.text)=>({reportId:'report0001',tree:{topics:[{name:'Access',subtopics:[{name:'Safety',claims:[{id:'c1',text:'Preserve access',quotes:[{commentId:source.id,text:quoteText}]}]}]}]}});
describe('workspace native imports',()=>{
 it.each(nativeAdapters)('%s: preserves typed native data in a reloadable workspace',tool=>{const p=project(),original=input(tool);const plan=load(p,original);expect(p.imports[0].bundle).toEqual(original.bundle);expect(allRecords(p)).toHaveLength(original.bundle.records.length);expect(validateProject(JSON.parse(JSON.stringify(p)))).toEqual(p);expect(allRecords(p).every(a=>!a.review.checked&&a.participantRef===null)).toBe(true);expect(plan.records.filter(a=>a.eligible).map(a=>a.id)).toEqual(roundSources(p).map(a=>a.id));});
 it('keeps Polis votes and method results out of voices while retaining counts',()=>{const p=project();load(p,input('delib-data'));expect(roundSources(p)).toHaveLength(1);expect(allRecords(p).filter(a=>a.kind==='method-result')).toHaveLength(2);expect(p.imports[0].bundle.records.find(r=>r.kind==='response').fields.count).toBe(1);expect(planTransfer(p,{tool:'tttc'}).inputs).toHaveLength(1);expect(JSON.stringify(p)).not.toContain('Fictional caregiver');});
 it('keeps unknown source chains out of Reply context even after review',()=>{const p=project();load(p,input('form'));load(p,input('tttc'));for(const a of allRecords(p))reviewRecord(p,a.id,{reviewer:'Facilitator'});expect(transferCandidates(p).context).toHaveLength(0);expect(()=>planTransfer(p,{tool:'reply'})).toThrow(/Review at least/);});
 it('completes a manual Form → TTTC → Reply file round trip without fabricating delivery',()=>{const p=project();load(p,input('form'));const source=roundSources(p)[0],t=transfer(p,'tttc');load(p,input('tttc',tttc(source)),{transferId:t.id});expect(traceVoice(p,source.id).map(a=>a.kind)).toEqual(['statement','quote','theme']);const replyTransfer=transfer(p,'reply');const data={loopId:'reply00001',questions:[{qid:'q1',text:source.text,sourceId:source.id}],loopbacks:[{qid:'q1',reply:'Draft: preserve accessible arrival.'}]};load(p,input('reply',data),{transferId:replyTransfer.id});expect(traceVoice(p,source.id).at(-1).kind).toBe('reply');expect(roundSources(p)).toHaveLength(1);expect(p.transfers.every(t=>t.history.at(-1).state==='exported')).toBe(true);expect(allRecords(p).at(-1).review.checked).toBe(false);});
 it('rejects wrong quote IDs/text and wrong Reply wording transactionally',()=>{const p=project();load(p,input('form'));const s=roundSources(p)[0],t=transfer(p,'tttc'),before=JSON.stringify(p);expect(()=>load(p,input('tttc',tttc(s,'invented')), {transferId:t.id})).toThrow(/Quote/);expect(()=>load(p,input('tttc',tttc({...s,id:'wrong'})),{transferId:t.id})).toThrow(/Quote/);expect(JSON.stringify(p)).toBe(before);load(p,input('tttc',tttc(s)),{transferId:t.id});const rt=transfer(p,'reply');expect(()=>load(p,input('reply',{questions:[{qid:1,text:'changed',sourceId:s.id}],loopbacks:[{qid:1,reply:'draft'}]}),{transferId:rt.id})).toThrow(/Reply question/);});
 it('retains proposal versions and shows changed method counts without asserting an amendment body',()=>{const p=project();load(p,input('proposals'));const original=structuredClone(p),v2=fixture('proposals');v2.proposals[0].version=3;v2.proposals[0].endorsements=4;const plan=load(p,input('proposals',v2));expect(plan.comparison.changed).toHaveLength(1);expect(allRecords(p)).toHaveLength(2);expect(allRecords(p)[0]).toEqual(allRecords(original)[0]);expect(allRecords(p).every(a=>a.supersedes===null)).toBe(true);for(const a of allRecords(p))reviewRecord(p,a.id,{reviewer:'Facilitator'});expect(transferCandidates(p).context.map(a=>a.id)).toEqual([allRecords(p)[1].id]);});
 it('never re-enables withdrawals or their local derivatives through later imports',()=>{const p=project(),data=input('form');load(p,data);const old=roundSources(p)[0];p.rounds[0].artifacts.push(record('theme','Access',{tool:'facilitator',id:'t'},[old.id]));const withdrawn=withdrawExchange(data.bundle,data.bundle.records[0].id,{by:'Host',reason:'Requested withdrawal'});load(p,{...data,bundle:withdrawn});expect(roundSources(p)).toHaveLength(0);expect(nativeRestrictions(p).withdrawn.has(old.id)).toBe(true);nextRound(p,{reason:'Review withdrawal',owner:'Host',date:'2026-12-01',phase:'learn'});load(p,data);expect(roundSources(p)).toHaveLength(0);expect(transferCandidates(p).context).toEqual([]);});
 it('deduplicates within a round, rejects stale previews and preserves old backups',()=>{const p=project();expect(validateProject(p)).toBe(p);const data=input('form'),plan=planNativeImport(p,data);p.goal='Changed purpose';expect(()=>applyNativeImport(p,plan)).toThrow(/preview again/);load(p,data);expect(()=>load(p,data)).toThrow(/already/);});
 it('rejects tampered snapshot mappings, native kinds, vote promotion, missing snapshots and simulation mismatch',()=>{const p=project();load(p,input('delib-data'));for(const corrupt of [q=>q.imports[0].mappings[1].workspaceId=q.imports[0].mappings[0].workspaceId,q=>q.rounds[0].artifacts[1].kind='statement',q=>q.rounds[0].artifacts[0].text='changed',q=>delete q.imports,q=>q.simulated=false]){const bad=structuredClone(p);corrupt(bad);expect(()=>validateProject(bad)).toThrow();}const real={...project(),simulated:false};expect(()=>load(real,input('form'))).toThrow(/Fictional/);});
 it('keeps absence distinct from withdrawal and supports non-topological exchange records',()=>{const p=project(),data=input('argument');data.bundle.records.reverse();load(p,data);expect(allRecords(p)[1].relations[0].ref).toBe(allRecords(p)[0].id);const reduced=structuredClone(data.bundle);reduced.records=reduced.records.filter(r=>!r.relations.length);const comparison=compareImports(p.imports[0],reduced);expect(comparison.absent).toHaveLength(1);expect(reduced.tombstones).toEqual([]);});
 it('reads and fingerprints files locally, rejects credentials and declared wrong format',async()=>{const data=await readNativeFile(JSON.stringify(fixture('form')),{tool:'form',simulated:true});expect(data.fileSha256).toMatch(/^[a-f0-9]{64}$/);expect(data.bundle.simulated).toBe(true);await expect(readNativeFile(JSON.stringify({...fixture('form'),adminToken:'secret'}),{tool:'form'})).rejects.toThrow(/credentials/);await expect(readNativeFile(JSON.stringify(fixture('form')),{tool:'exchange'})).rejects.toThrow(/Choose/);});
});

it('connects the current Pocket Polis CSV adapter to workspace without promoting seed statements',async()=>{
 const {parsePocketPolisExports,buildPocketPolisBundle}=await import('../public/pocket-polis-data-core.js');
 const {pocketPolisBundleToDelibData}=await import('../public/delib-data-core.js');
 const statementsCsv='statement_id,text,status,is_seed,agrees,disagrees,passes,created_at\n1,Organizer prompt,approved,1,1,0,0,2026-09-01T00:00:00Z\n2,Keep the accessible bay.,approved,0,0,1,0,2026-09-01T00:00:00Z';
 const votesCsv='participant,statement_id,vote,updated_at\np1,1,1,2026-09-01T00:00:00Z\np1,2,-1,2026-09-01T00:00:00Z';
 const bundle=buildPocketPolisBundle({title:'School access',description:'Synthetic test',reportUrl:'https://polis.mashbean.net/r/abc123def4',parsed:parsePocketPolisExports({statementsCsv,votesCsv}),exportedAt:'2026-09-01T00:00:00Z',files:[{role:'statements',name:'statements.csv',size:statementsCsv.length,sha256:'a'.repeat(64)},{role:'votes',name:'votes.csv',size:votesCsv.length,sha256:'b'.repeat(64)}]});
 const p=project();load(p,input('delib-data',pocketPolisBundleToDelibData(bundle)));expect(roundSources(p).map(a=>a.text)).toEqual(['Keep the accessible bay.']);expect(p.imports[0].bundle.records.filter(r=>r.kind==='response')).toHaveLength(2);
});

it('quarantines an unsupported synthesis without a source chain',()=>{const p=project(),data=input('tttc');data.bundle.records.find(r=>r.kind==='theme').relations=[];load(p,data);for(const a of allRecords(p))reviewRecord(p,a.id,{reviewer:'Host'});expect(transferCandidates(p).context).toEqual([]);});
